Particular/NServiceBus.Persistence.CosmosDB

- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/SetupFixture.cs
Cannot be used with Serverless tier
> Remove auto-scaling

- src/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests/ConfigureEndpointCosmosDBPersistence.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/ApiApprovals.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Persistence.CosmosDB.Tests/NServiceBus.Persistence.CosmosDB.Tests.csproj
- src/NServiceBus.Persistence.CosmosDB/Config/CosmosDbPersistenceConfig.cs
This also removes the extra overload for `DefaultContainer`.
> Add API approval test

- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/SetupFixture.cs
- src/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/SetupFixture.cs
- src/NServiceBus.Persistence.CosmosDB/CosmosDBPersistenceInstaller.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/Operation.cs
- src/NServiceBus.Persistence.CosmosDB/Utility/CosmosDBContractResolver.cs
- src/SharedAcceptanceTests.All/SharedAcceptanceTests.All.txt
- src/SharedAcceptanceTests.RequirePartitionKey/NServiceBusAcceptanceTest.cs
- src/SharedAcceptanceTests.RequirePartitionKey/SharedAcceptanceTests.RequirePartitionKey.txt
- src/SharedAcceptanceTests.RequirePartitionKey/TransactionalBatchCounterHandler.cs
- src/SharedAcceptanceTests.RequirePartitionKey/When_using_synchronized_session_via_container_and_storage_session_extension.cs
- src/SharedAcceptanceTests.RequirePartitionKey/When_using_synchronized_session_via_container_and_storage_session_fails.cs
Addressed https://github.com/Particular/NServiceBus.Persistence.CosmosDB/pull/41#issuecomment-695048136
> Test transactional batch with multiple operations

- src/NServiceBus.Persistence.CosmosDB/Outbox/MetadataExtensions.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxOperations.cs
- src/NServiceBus.Persistence.CosmosDB/Saga/MetadataExtensions.cs
- src/NServiceBus.Persistence.CosmosDB/Saga/SagaOperations.cs
Consistently writes the full type name to outbox record and saga
> Add full type name to metadata

- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/ConfigureEndpointCosmosDBPersistence.cs
> Reintroduce InsertBefore to make sure behavior order is deterministic

- src/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter.csproj
- src/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter/Program.cs
- src/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter/ToolVersion.cs
The tool to check if there's a later version available and should be used.
> Enforce usage of the latest tool version

- src/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter.AcceptanceTests/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/NServiceBus.Persistence.CosmosDB.PersistenceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.Tests/NServiceBus.Persistence.CosmosDB.Tests.csproj
- src/NServiceBus.Persistence.CosmosDB/NServiceBus.Persistence.CosmosDB.csproj
[Performance and bug fixes](https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.14.0) in the SDK.
> Bump Cosmos DB SDK

- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/ExtendedOutboxStorageTests.cs
- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/PersistenceTestsConfiguration.cs
- src/NServiceBus.Persistence.CosmosDB/Installer.cs
> Set default time to live on the container to enable individual record TTL

- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/NServiceBus.Persistence.CosmosDB.PersistenceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.Tests/NServiceBus.Persistence.CosmosDB.Tests.csproj
- src/NServiceBus.Persistence.CosmosDB/NServiceBus.Persistence.CosmosDB.csproj
Should unlock https://github.com/Particular/Particular.AzureTable.Export/pull/30
> Update to latest alphas

- .github/workflows/ci.yml
Note that I started making these changes and, not realizing the branch protection was not set to include administrators, accidentally committed to master. Previous changes are in https://github.com/Particular/NServiceBus.Persistence.CosmosDB/commit/fe859fdd149d44983998b03e54dfee16723ffead .
> Finish allowing CI to switch regions

- src/NServiceBus.Persistence.CosmosDB/FodyWeavers.xml
adding line ending to weavers file
> Adding HideObsoleteMembers to weavers

- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PessimisticLock.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PessimisticLock.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.Tests/NServiceBus.Persistence.CosmosDB.Tests.csproj
- src/NServiceBus.Persistence.CosmosDB/NServiceBus.Persistence.CosmosDB.csproj
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxBehavior.cs
- src/NServiceBus.Persistence.CosmosDB/Saga/SagaPersister.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/Operation.cs
> Adjust LangVersion to 10.0

- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/SynchronizedStorage.cs
> Switch to using ICompletableSynchronizedStorageSession

- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PessimisticLock.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PessimisticLock.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests.csproj
> Fix build warnings

- src/NServiceBus.Persistence.CosmosDB.TransactionalSession.AcceptanceTests/NServiceBus.Persistence.CosmosDB.TransactionalSession.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.TransactionalSession.Tests/NServiceBus.Persistence.CosmosDB.TransactionalSession.Tests.csproj
Updates the release branch to use the latest Core version containing transactional session related fixes.
> Verify Core 8.x changes

- .component-package.yml
- .component_package.yml
This PR adds in a metadata file to the repo that specifies the component packages that are generated as part of the assets in release work flow
> metadata component package yml

- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/NServiceBus.Persistence.CosmosDB.PersistenceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PessimisticLock.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PessimisticLock.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/When_custom_partition_key_extractor_from_headers_registered_via_api.cs
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/When_custom_partition_key_extractor_from_headers_registered_via_di.cs
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/When_fluent_extractor_registered_via_api.cs
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/When_using_outbox_control_message.cs
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/When_using_outbox_synchronized_session_via_container_partial.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/NServiceBus.Persistence.CosmosDB.Tests.csproj
- src/NServiceBus.Persistence.CosmosDB.TransactionalSession.AcceptanceTests/NServiceBus.Persistence.CosmosDB.TransactionalSession.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.TransactionalSession.AcceptanceTests/When_using_transactional_session.cs
- src/NServiceBus.Persistence.CosmosDB.TransactionalSession.Tests/NServiceBus.Persistence.CosmosDB.TransactionalSession.Tests.csproj
This PR contains all changes related to NUnit4 upgrade including all required dependencies.
The following packages are checked for necessary upgrades but might not necessarily be in the change set if they are not present:
- NServiceBus
- NServiceBus.AcceptanceTesting
- NServiceBus.AcceptanceTests.Sources
- NServiceBus.TransportTests.Sources
- NUnit
In addition, some manual interventions are done when applicable.
> Upgrading to NUnit4 including all required dependencies

- src/NServiceBus.Persistence.CosmosDB.Tests/Outbox/OutboxPersisterTests.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/Saga/SagaPersisterTests.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/LogicalOutboxBehavior.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxContainerExtensions.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxOperations.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxPersister.cs
- src/NServiceBus.Persistence.CosmosDB/Saga/SagaPersister.cs
Resolves:
- https://github.com/Particular/NServiceBus.Persistence.CosmosDB/issues/855
> Ensure non succesful SDK status codes are handled gracefully

- src/NServiceBus.Persistence.CosmosDB/Saga/SagaPersister.cs
I have already applied that change to #856 and #857
> Use random shared instead

- src/NServiceBus.Persistence.CosmosDB.Tests/Outbox/OutboxPersisterTests.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/Saga/SagaPersisterTests.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/LogicalOutboxBehavior.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxContainerExtensions.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxOperations.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxPersister.cs
- src/NServiceBus.Persistence.CosmosDB/Saga/SagaPersister.cs
Backport of:
- #854
to `release-3.0`
> Ensure non succesful SDK status codes are handled gracefully (#854)

- src/NServiceBus.Persistence.CosmosDB/Saga/SagaOperations.cs
Backport of:
- #864
To `release-3.1`
> Improve the saga conflict operation error messages

- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/PersistenceTestsConfiguration.cs
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/When_subscribers_handles_the_same_control_event.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Persistence.CosmosDB.Tests/Outbox/LogicalOutboxBehaviorTests.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/Outbox/OutboxPersisterTests.cs
- src/NServiceBus.Persistence.CosmosDB.TransactionalSession/CosmosTransactionalSessionExtensions.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/CosmosOutboxSettingsExtensions.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/LogicalOutboxBehavior.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxPersistenceConfiguration.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxPersister.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxStorage.cs
Backport of:
-  https://github.com/Particular/NServiceBus.Persistence.CosmosDB/pull/896
Which fixes for the `3.1` branch:
- https://github.com/Particular/NServiceBus.Persistence.CosmosDB/issues/893
> Change Outbox to use synthetic partition key - v3.1

- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/PersistenceTestsConfiguration.cs
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/When_subscribers_handles_the_same_control_event.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Persistence.CosmosDB.Tests/Outbox/LogicalOutboxBehaviorTests.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/Outbox/OutboxPersisterTests.cs
- src/NServiceBus.Persistence.CosmosDB.TransactionalSession/CosmosTransactionalSessionExtensions.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/CosmosOutboxSettingsExtensions.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxBehavior.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxPersistenceConfiguration.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxPersister.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxStorage.cs
Backport of:
-  https://github.com/Particular/NServiceBus.Persistence.CosmosDB/pull/896
Which fixes for the `2.0` branch:
- https://github.com/Particular/NServiceBus.Persistence.CosmosDB/issues/893
> Change Outbox to use synthetic partition key - v2.0
