- src/NServiceBus.Persistence.CosmosDB/Saga/SagaPersister.cs
Bob and I took on a transient Newtonsoft.Json dependency used by CosmosDB.
We should consider providing a configuration API for the persistence to take a custom serializer settings to pass on to CosmosDB client the persistence will use.
I've left the idea to delete items using TTL out of this PR but we could take the similar approach to the one used in the `Save` method, adding a property `ttl` with the desired amount of time (in seconds) after which the item should be auto-deleted.
> Switch to Stream API

- src/NServiceBus.Persistence.CosmosDB/Config/CosmosDbPersistenceConfig.cs
- src/NServiceBus.Persistence.CosmosDB/Config/SettingsKeys.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/ICosmosDBStorageSession.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/SynchronizedStorage.cs
- src/SharedAcceptanceTests.RequirePartitionKey/When_using_outbox_synchronized_session_via_container.cs
- src/SharedAcceptanceTests.RequirePartitionKey/When_using_synchronized_session_via_container.cs
A) compliant with other persisted approaches
B) Registering an SDK type directly is not a good idea because customers can already have it registered
C) In order to address the above you had to introduce another setting method
D) It violates the design principles we have for DI support
I changed the tests to use the storage session directly. I think that was the misleading part that caused us down the path of wanting to remove it
> Revert di support changes

- src/NServiceBus.Persistence.CosmosDB/Saga/SagaPersister.cs
SagaPersister get logic cannot handle cases when messages are still in flight but no saga data has been created or imported yet.
I detected this case while sending thousands of messages to the server and then migrate the server while there where still messages in the queue that would start a saga.
> Fix saga persister get problem

- src/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter.csproj
The longer package name combined with the path .NET Tool is creating is easily exceeding 260 characters even when installed as a local tool.
To avoid problems, it's better to shorten the name.
> Shorten tool package name

- src/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter.AcceptanceTests/NServiceBus.Persistence.CosmosDB.AzureStorageSagaExporter.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/NServiceBus.Persistence.CosmosDB.PersistenceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.Tests/NServiceBus.Persistence.CosmosDB.Tests.csproj
- src/NServiceBus.Persistence.CosmosDB/NServiceBus.Persistence.CosmosDB.csproj
Cosmos DB client 3.13.0 has quite a few performance improvements and a bug fix related to the batch API which the persistence depends upon.
https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.13.0
> Bump Cosmos client

- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/When_using_outbox_synchronized_session_via_container_partial.cs
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/When_using_outbox_synchronized_session_via_container_partial.cs
- src/NServiceBus.Persistence.CosmosDB.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Persistence.CosmosDB.Tests/SynchronizedStorage/TestableCosmosSynchronizedStorageSessionTests.cs
- src/NServiceBus.Persistence.CosmosDB/Config/PartitionKeyPath.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/ICosmosDBStorageSession.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/IWorkWithSharedTransactionalBatch.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/SharedTransactionalBatch.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/StorageSession.cs
- src/NServiceBus.Persistence.CosmosDB/Testing/TestableCosmosSynchronizedStorageSession.cs
- src/SharedAcceptanceTests.RequirePartitionKey/When_using_outbox_synchronized_session_via_container.cs
Based on customer feedback.
There are basically two options:
- Make container holder public
- Provide all the necessary information on the storage session
I opted for the latter because I think then the storage session is sufficiently self-contained so that any more complex workflow can fully rely on DI patterns to create advanced things like identity map
> Expose Container, PartitionKey, PartitionKeyPath on the storage session

- src/NServiceBus.Persistence.CosmosDB.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Persistence.CosmosDB.Tests/SynchronizedStorage/TestableCosmosSynchronizedStorageSessionTests.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/SynchronizedStorageSessionExtensions.cs
- src/SharedAcceptanceTests.RequirePartitionKey/When_using_synchronized_session_via_container_and_storage_session_extension.cs
- src/SharedAcceptanceTests.RequirePartitionKey/When_using_synchronized_session_via_container_and_storage_session_fails.cs
This PR fully exposes the synchronized storage session instead of just the transactional batch.
Previously we only exposed the transactional batch because that was the only thing the storage session provided and thus this approach was similar to MongoDB. 
With the introduction of #64 the storage session exposed now much more valuable information than just the batch. All other persisters that expose multiple things on the storage session also return the storage session itself therefore I think we should follow that as well and expose the full session.
> Fully expose the whole storage session when accessed via SynchronizedStorageSession

- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/StorageSession.cs
- src/SharedAcceptanceTests.All/When_regular_handler_with_no_container_information.cs
> Make container information non-mandatory for handlers that don't require storage access

- src/NServiceBus.Persistence.CosmosDB.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Persistence.CosmosDB/Config/IProvideCosmosClient.cs
- src/SharedAcceptanceTests.All/When_custom_provider_registered.cs
While doing the Azure enhancement release we realized having the providers in the root namespace is problematic as soon as you have multiple components that want to register the same third party type. So we decided to move the providers to the component namespace.
> Move the provider to the component namespace

- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/TransactionalBatchOperationException.cs
When not already providing a message to the `TransactionalBatchOperationException` ctor, error information from `TransactionalBatchOperationException` from stack traces are basically useless as there is no information from the `Result` property mentioned. This is a small change to at least include the HTTP status code to give a hint of the involved issue for better diagnosis.
> Add status code to TransactionalBatchOperationException message

- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxStorage.cs
- src/NServiceBus.Persistence.CosmosDB/Saga/SagaPersistence.cs
- src/NServiceBus.Persistence.CosmosDB/Utility/NonNativePubSubCheck.cs
Acts as a fix to https://github.com/Particular/NServiceBus.Persistence.CosmosDB/issues/186 by preventing the persistence from running in an unsupported configuration.
> Throw if endpoint configured for message-driven pub/sub

- src/NServiceBus.Persistence.CosmosDB.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Persistence.CosmosDB/Config/PartitionKeyPath.cs
- src/NServiceBus.Persistence.CosmosDB/SynchronizedStorage/Operation.cs
The cardinality of the partition key paths is low, so we can cache the path and the segments
> Cache partition key path and segments

- src/NServiceBus.Persistence.CosmosDB.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.Persistence.CosmosDB.Tests/Transaction/ContainerInformationExtractorTests.cs
- src/NServiceBus.Persistence.CosmosDB/Transaction/ContainerInformationExtractor.Headers.cs
- src/NServiceBus.Persistence.CosmosDB/Transaction/ContainerInformationExtractor.Messages.cs
- src/NServiceBus.Persistence.CosmosDB/Transaction/TransactionInformationConfiguration.ContainerInformation.cs
- src/NServiceBus.Persistence.CosmosDB/Transaction/TransactionInformationConfiguration.PartitionKey.cs
Adds a helpful overload for simple scenarios where a `ContainerInformation` instance can be used based on the message type.
> Add overload to provide a ContainerInformation instance

- src/NServiceBus.Persistence.CosmosDB.Tests/NServiceBus.Persistence.CosmosDB.Tests.csproj
- src/NServiceBus.Persistence.CosmosDB.Tests/Saga/SagaIdGeneratorTests.cs
- src/NServiceBus.Persistence.CosmosDB/NServiceBus.Persistence.CosmosDB.csproj
- src/NServiceBus.Persistence.CosmosDB/Saga/CosmosSagaIdGenerator.cs
|                             Method |     Mean |   Error |  StdDev | Ratio |  Gen 0 | Allocated |
|----------------------------------- |---------:|--------:|--------:|------:|-------:|----------:|
|                   Original| 729.7 ns | 2.78 ns | 2.60 ns |  1.00 | 0.0458 |     392 B |
|                        Netframework Optimized | 720.4 ns | 6.16 ns | 5.76 ns |  0.99 | 0.0260 |     224 B |
| Netcore Optimized| 624.1 ns | 3.22 ns | 2.85 ns |  0.86 | 0.0146 |     128 B |
This is something for the master branch I wanted to avoid pushing into the current release just yet. 
The benchmark https://github.com/danielmarbach/MicroBenchmarks/commit/8c5fd4b1671f6aad15f74a238937e9234ebd90f9
> Optimize deterministic ID creation

- .github/workflows/ci.yml
- src/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.LogicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests/NServiceBus.Persistence.CosmosDB.NonTransactionalSagas.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PersistenceTests/NServiceBus.Persistence.CosmosDB.PersistenceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PessimisticLock.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PessimisticLock.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests.csproj
- src/NServiceBus.Persistence.CosmosDB.Tests/NServiceBus.Persistence.CosmosDB.Tests.csproj
- src/NServiceBus.Persistence.CosmosDB/NServiceBus.Persistence.CosmosDB.csproj
- src/NServiceBus.Persistence.CosmosDB/Saga/CosmosSagaIdGenerator.cs
Removes .NET Core app 3.1 in favor of .NET 6.
> Update .net targets

- src/NServiceBus.Persistence.CosmosDB.Tests/Outbox/PendingTransportOperationsExtensionsTests.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxBehavior.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/PendingTransportOperationsExtensions.cs
> Make sure PendingTransportOperations clearing doesn't leak state from previous executions

- src/NServiceBus.Persistence.CosmosDB/Saga/CosmosSagaIdGenerator.cs
This is a follow-up on #300. It removes the unnecessary temporary string allocation. The results are pretty nice
Existing https://github.com/Particular/NServiceBus.Persistence.CosmosDB/blob/master/src/NServiceBus.Persistence.CosmosDB.Tests/Saga/SagaIdGeneratorTests.cs verifies backward compatibility.
> Optimize SagaId generator to no longer allocate the intermediate string

- src/NServiceBus.Persistence.CosmosDB.TransactionalSession/CosmosTransactionalSession.cs
- src/NServiceBus.Persistence.CosmosDB/Transaction/Transaction.cs
Make sure the `TransactionInformationConfiguration` is added by the defaults so that other features can add in their default implementations of partition key and container extractors without running into ordering issues.
> Set TransactionInformationConfiguration as defaults

- src/NServiceBus.Persistence.CosmosDB.PhysicalOutbox.AcceptanceTests/When_using_outbox_control_message.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxBehavior.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxPersister.cs
- src/NServiceBus.Persistence.CosmosDB/Outbox/SetAsDispatchedHolderExtensions.cs
- src/SharedAcceptanceTests.RequirePartitionKey/When_no_container_information_is_configured.cs
- src/SharedAcceptanceTests.RequirePartitionKey/When_no_partition_key_is_configured.cs
You are affected if:
- You have the [outbox enabled](https://docs.particular.net/nservicebus/outbox/)
- You are using a transport requiring [message-driven (persistence-based) publish and subscribe](https://docs.particular.net/nservicebus/messaging/publish-subscribe/#mechanics-message-driven-persistence-based) _or_
- You are using [callbacks](https://docs.particular.net/nservicebus/messaging/callbacks) with an [integer](https://docs.particular.net/nservicebus/messaging/callbacks#using-callbacks-integers) or [enum](https://docs.particular.net/nservicebus/messaging/callbacks#using-callbacks-enum) response
When the transport receives a [control message](https://docs.particular.net/nservicebus/messaging/headers#messaging-interaction-headers-nservicebus-controlmessage), the partition key …
> Processing a control message causes the outbox to throw a null reference exception

- .component-package.yml
Reverts Particular/NServiceBus.Persistence.CosmosDB#721
Reverting this PR as component packages that are generated as part of the assets in release work flow will be read from centralized file
> Revert "metadata component package yml"

- src/NServiceBus.Persistence.CosmosDB/Saga/SagaOperations.cs
Having all the messages indicate there is a problem with "completing" the saga is confusing when you need to troubleshoot a potential problem with concurrent saga updates. This improves the error messages slightly.
> Improve the saga conflict operation messages
